spin_manifest_version = 2

[application]
name = "information-dynamics-oracle"
version = "0.1.0"
authors = ["bmorphism <bmorphism@users.noreply.github.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "information-dynamics-oracle"

[component.information-dynamics-oracle]
source = "target/wasm32-wasip1/release/information-dynamics_oracle.wasm"
allowed_outbound_hosts = []
[component.information-dynamics-oracle.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
