# Ruler Configuration File
# See https://ai.intellectronica.net/ruler for documentation.

# Enable ALL ruler-supported platforms for maximum deployment coverage
default_agents = ["claude", "cursor", "aider", "copilot", "windsurf", "cline", "codex", "firebase", "openhands", "gemini-cli", "jules", "junie", "augmentcode", "kilocode", "opencode"]

# --- Agent Specific Configurations ---
# You can enable/disable agents and override their default output paths here.
# Use lowercase agent identifiers: copilot, claude, codex, cursor, windsurf, cline, aider, kilocode

# Enable all supported AI agents for maximum platform coverage

[agents.claude]
enabled = true
output_path = "CLAUDE.md"

[agents.cursor]
enabled = true
output_path = ".cursor/rules/ruler_cursor_instructions.mdc"

[agents.aider]
enabled = true
output_path_instructions = "ruler_aider_instructions.md"
output_path_config = ".aider.conf.yml"

[agents.copilot]
enabled = true
output_path = ".github/copilot-instructions.md"

[agents.windsurf]
enabled = true
output_path = ".windsurf/rules/ruler_windsurf_instructions.md"

[agents.cline]
enabled = true
output_path = ".clinerules"

[agents.codex]
enabled = true
output_path = "AGENTS.md"
output_path_config = ".codex/config.toml"

[agents.firebase]
enabled = true
output_path = ".idx/airules.md"

[agents.openhands]
enabled = true
output_path = ".openhands/microagents/repo.md"

[agents.gemini-cli]
enabled = true
output_path = "GEMINI.md"

[agents.jules]
enabled = true
output_path = "AGENTS.md"

[agents.junie]
enabled = true
output_path = ".junie/guidelines.md"

[agents.augmentcode]
enabled = true
output_path = ".augment/rules/ruler_augment_instructions.md"

[agents.kilocode]
enabled = true
output_path = ".kilocode/rules/ruler_kilocode_instructions.md"

[agents.opencode]
enabled = true
output_path = "AGENTS.md"

# [agents.firebase]
# enabled = true
# output_path = ".idx/airules.md"

# [agents.gemini-cli]
# enabled = true

# [agents.kilocode]
# enabled = true
# output_path = ".kilocode/rules/ruler_kilocode_instructions.md"
